# Project Scenario:
An international firm that is looking to expand its business in different countries across the world has recruited you. You have been hired as a junior Data Engineer and are tasked with creating a script that can extract the list of the top 10 largest economies of the world in descending order of their GDPs in Billion USD (rounded to 2 decimal places), as logged by the International Monetary Fund (IMF).(This is a practice project given in IBM python data science course)

The required data seems to be available on the URL mentioned below:

[https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29](https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29)

### Exercise 1
Extract the required GDP data from the given URL  
Extract tables from webpage using Pandas. Retain table number 3 as the required dataframe.  
Replace the column headers with column numbers  
Retain columns with index 0 and 2 (name of country and value of GDP quoted by IMF)  
Retain the Rows with index 1 to 10, indicating the top 10 economies of the world.  
Assign column names as "Country" and "GDP (Million USD)"

In [1]:
import pandas as pd
import numpy as np
URL = "https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"
tables = pd.read_html(URL)
df = tables[3]
df

    Country/Territory UN region IMF[1][13]            World Bank[14]  \
    Country/Territory UN region   Estimate       Year       Estimate
0               World         —  105568776       2023      100562011
1       United States  Americas   26854599       2023       25462700
2               China      Asia   19373586  [n 1]2023       17963171
3               Japan      Asia    4409738       2023        4231141
4             Germany    Europe    4308854       2023        4072192
..                ...       ...        ...        ...            ...
209          Anguilla  Americas          —          —              —
210          Kiribati   Oceania        248       2023            223
211             Nauru   Oceania        151       2023            151
212        Montserrat  Americas          —          —              —
213            Tuvalu   Oceania         65       2023             60

               United Nations[15]
          Year           Estimate       Year
0         2022           96698005       2021
1         2022           23315081       2021
2    [n 3]2022           17734131  [n 1]2021
3         2022            4940878       2021
4         2022            4259935       2021
..         ...                ...        ...
209          —                303       2021
210       2022                227       2021
211       2022                155       2021
212          —                 72       2021
213       2022                 60       2021

[214 rows x 8 columns]

In [2]:
import pandas as pd
import numpy as np
URL = "https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"
tables = pd.read_html(URL)
df = tables[3]
df.columns = range(df.shape[1])
df

,0,1,2,3,4,5,6,7
0,World,—,105568776,2023,100562011,2022,96698005,2021
1,United States,Americas,26854599,2023,25462700,2022,23315081,2021
2,China,Asia,19373586,[n 1]2023,17963171,[n 3]2022,17734131,[n 1]2021
3,Japan,Asia,4409738,2023,4231141,2022,4940878,2021
4,Germany,Europe,4308854,2023,4072192,2022,4259935,2021
...,...,...,...,...,...,...,...,...
209,Anguilla,Americas,—,—,—,—,303,2021
210,Kiribati,Oceania,248,2023,223,2022,227,2021
211,Nauru,Oceania,151,2023,151,2022,155,2021
212,Montserrat,Americas,—,—,—,—,72,2021
213,Tuvalu,Oceania,65,2023,60,2022,60,2021

In [3]:
df = df[[0,2]]
df

                 0          2
0            World  105568776
1    United States   26854599
2            China   19373586
3            Japan    4409738
4          Germany    4308854
..             ...        ...
209       Anguilla          —
210       Kiribati        248
211          Nauru        151
212     Montserrat          —
213         Tuvalu         65

[214 rows x 2 columns]

In [4]:
df = df.head(11)
df

                 0          2
0            World  105568776
1    United States   26854599
2            China   19373586
3            Japan    4409738
4          Germany    4308854
5            India    3736882
6   United Kingdom    3158938
7           France    2923489
8            Italy    2169745
9           Canada    2089672
10          Brazil    2081235

In [5]:
df.columns = ["County","GDP (Million USD)"]
df

            County GDP (Million USD)
0            World         105568776
1    United States          26854599
2            China          19373586
3            Japan           4409738
4          Germany           4308854
5            India           3736882
6   United Kingdom           3158938
7           France           2923489
8            Italy           2169745
9           Canada           2089672
10          Brazil           2081235

## Exercise 2
Modify the GDP column of the DataFrame, converting the value available in Million USD to Billion USD. Use the round() method of Numpy library to round the value to 2 decimal places. Modify the header of the DataFrame to GDP (Billion USD).

Change the data type of the 'GDP (Million USD)' column to integer. Use astype() method.  
Convert the GDP value in Million USD to Billion USD  
Use numpy.round() method to round the value to 2 decimal places.  
Rename the column header from 'GDP (Million USD)' to 'GDP (Billion USD)'

In [6]:
df['GDP (Million USD)'] = df['GDP (Million USD)'].astype(int)

In [7]:
df[['GDP (Million USD)']] = df[['GDP (Million USD)']]/1000
df

            County  GDP (Million USD)
0            World         105568.776
1    United States          26854.599
2            China          19373.586
3            Japan           4409.738
4          Germany           4308.854
5            India           3736.882
6   United Kingdom           3158.938
7           France           2923.489
8            Italy           2169.745
9           Canada           2089.672
10          Brazil           2081.235

In [8]:
df[['GDP (Million USD)']] = np.round(df[['GDP (Million USD)']],2)
df

            County  GDP (Million USD)
0            World          105568.78
1    United States           26854.60
2            China           19373.59
3            Japan            4409.74
4          Germany            4308.85
5            India            3736.88
6   United Kingdom            3158.94
7           France            2923.49
8            Italy            2169.74
9           Canada            2089.67
10          Brazil            2081.24

In [9]:
df.rename(columns = {'GDP (Million USD)' : 'GDP (Billion USD)'})

            County  GDP (Billion USD)
0            World          105568.78
1    United States           26854.60
2            China           19373.59
3            Japan            4409.74
4          Germany            4308.85
5            India            3736.88
6   United Kingdom            3158.94
7           France            2923.49
8            Italy            2169.74
9           Canada            2089.67
10          Brazil            2081.24

## Exercise 3
Load the DataFrame to the CSV file named "Largest_economies.csv"

In [10]:
df.to_csv('./Largest_economies.csv')